### ISSUE TITLE
语音渠道启动不了

### ISSUE THREAD

**Issue by qq31682216** [chatopera/cosin#129]
# 描述
按照https://github.com/chatopera/cosin/wiki/%E8%AF%AD%E9%9F%B3%E6%B8%A0%E9%81%93
的配置，报错：
/root/waihu/cosin/cc-switch/app/node_modules/minio/dist/main/minio.js:119
      throw new errors.InvalidEndpointError('Invalid endPoint : ' + params.endPoint);
      ^
InvalidEndpointError: Invalid endPoint : http://10.80.185.10:9000
    at new Client (/root/waihu/cosin/cc-switch/app/node_modules/minio/dist/main/minio.js:119:13)
我已经启动了服务

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by qq31682216** [comment]
上一个错误已经搞定，但是npm start 后报错如下：
[root@AY14061410230729812aZ app]# npm start

> cc-switch@1.0.0 start /home/sre/waihu/cosin/cc-switch/app
> node index.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'lodash.defaults'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sre/waihu/cosin/cc-switch/app/node_modules/ioredis/built/utils/lodash.js:4:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cc-switch@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cc-switch@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kylezhang** [comment]
看看lodash.js是否正确的按照了。

**Comment by bobokingbao** [comment]
请问第一个问题是如何解决的，我也遇到的一样的问题

**Comment by Samurais** [comment]
5.0.0版本以后，语音渠道不开源。
