### ISSUE TITLE
[cc] 访客端不能在手机上传图片

### ISSUE THREAD

**Issue by Samurais** [chatopera/cosin#131]
# 描述

## 现在行为

![image](https://user-images.githubusercontent.com/3538629/47998450-51b57780-e13a-11e8-9e4e-db9df8a40f95.png)

```
contact-center_1  | 2018-11-05 20:27:32.481 [nioEventLoopGroup-3-3] INFO  com.chatopera.cc.exception.UCKeFuExceptionListener - Connection reset by peer
contact-center_1  | 2018-11-05 20:31:20.280 [http-nio-8080-exec-11] ERROR druid.sql.Statement - {conn-10003, pstmt-21148} execute error. insert into cs_stream_file (cooperation, data, mime, name, thumbnail, id) values (?, ?, ?, ?, ?, ?)
contact-center_1  | com.mysql.jdbc.PacketTooBigException: Packet for query is too large (6176726 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
contact-center_1  |     at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3756)
contact-center_1  |     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2449)
contact-center_1  |     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
contact-center_1  |     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)
contact-center_1  |     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
contact-center_1  |     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2450)
contact-center_1  |     at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2371)
```

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
https://stackoverflow.com/questions/39369367/increase-max-allowed-packet-size-in-mysql-docker

```
services:
  data:
    image: "mysql:5.7.20"
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
```
