### ISSUE TITLE
客服端上传文件或图片保存500

### ISSUE THREAD

**Issue by 654409314** [chatopera/cosin#149]
# 描述
客服端上传文件或图片保存500
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Nov 13 18:18:11 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
Could not parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [C:\Users\abc\AppData\Local\Temp\tomcat.4232277652217390644.8950\work\Tomcat\localhost\ROOT\..\data] is not valid
## 现在行为
![image](https://user-images.githubusercontent.com/41300336/48406983-c4dd7000-e770-11e8-8fc3-16f96541fa75.png)

2018-11-13 19:08:28.959 [http-nio-8950-exec-5] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.io.IOException: The temporary upload location [C:\Users\abc\AppData\Local\Temp\tomcat.4232277652217390644.8950\work\Tomcat\localhost\ROOT\..\data] is not valid] with root cause
java.io.IOException: The temporary upload location [C:\Users\abc\AppData\Local\Temp\tomcat.4232277652217390644.8950\work\Tomcat\localhost\ROOT\..\data] is not valid
	at org.apache.catalina.connector.Request.parseParts(Request.java:2846)
	at org.apache.catalina.connector.Request.parseParameters(Request.java:3215)
	at org.apache.catalina.connector.Request.getParameter(Request.java:1145)
	at org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:381)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
## 预期行为

# 解决方案
 未解决
# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by kylezhang** [comment]
我测试了下，是可以的
## 访客端
![image](https://user-images.githubusercontent.com/3679798/48412464-b64a8500-e77f-11e8-8f4c-7bd20f5c8941.png)

## 座席端
![image](https://user-images.githubusercontent.com/3679798/48412447-a16df180-e77f-11e8-97ff-6216467e89b1.png)

**Comment by 654409314** [comment]
application.propertise中不能注释掉web.upload-path
原来的默认值为../data导致生成的路径根本找不到是一个无效路径，要么直接指定绝对路径要么置为空
将其值置为空：web.upload-path=
