### ISSUE TITLE
使用docker compose 启动后，cc不能成功运行，es报错

### ISSUE THREAD

**Issue by Samurais** [chatopera/cosin#176]
# 描述

## cc错误

```
contact-center_1  |     at java.lang.Thread.run(Thread.java:748)
contact-center_1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchDataAutoConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticsearchClient' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'elasticsearchClient' threw exception; nested exception is java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: newWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in functioncontact-center_1  |     at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)                    contact-center_1  |     at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)          contact-center_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)                                                                                                                                         contact-center_1  |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
```

## es错误
```
unable to install syscall filter: seccomp unavailable: your kernel is buggy an
d you should upgrade
```

![image](https://user-images.githubusercontent.com/3538629/51454089-e44ed580-1d7d-11e9-8480-253d6add5062.png)

## 预期行为

# 解决方案

# 环境

Ubuntu 16.04 Server

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
duplicated with #181
