### ISSUE TITLE
集成聊天机器人出错

### ISSUE THREAD

**Issue by hj123hj** [chatopera/cosin#185]
# 描述
集成聊天机器人时，弹出对话框，（1）确保网络联通，（2）确保聊天机器人被创建，确保 ID和secret正确
但是我保证3个问题 都不存在，且代码是最新的
## 现在行为
![捕获](https://user-images.githubusercontent.com/28702031/55966883-d6895c00-5cab-11e9-93a2-3a61077f2617.PNG)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
Java控制台有什么错误消息？

**Comment by Samurais** [comment]
如果您使用我们推荐的部署方式，查看Java控制台的日志：
```
docker-compose logs -f contact-center
```

**Comment by hj123hj** [comment]
报错内容：
2019-04-13 22:14:40.312 [http-nio-8035-exec-7] ERROR c.c.cc.app.handler.api.rest.ApiChatbotController - bot create error
com.chatopera.bot.exception.ChatbotException: com.chatopera.bot.exception.ChatbotException: com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.chatopera.bot.sdk.Chatbot.exists(Chatbot.java:131)
	at com.chatopera.cc.app.handler.api.rest.ApiChatbotController.create(ApiChatbotController.java:491)
	at com.chatopera.cc.app.handler.api.rest.ApiChatbotController.operations(ApiChatbotController.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.chatopera.cc.app.config.ApiRequestMatchingFilter.doFilter(ApiRequestMatchingFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.chatopera.cc.app.config.DelegateRequestMatchingFilter.doFilter(DelegateRequestMatchingFilter.java:61)

**Comment by Samurais** [comment]
部署春松过程是怎么样的？不是我们发布的docker部署的吧？
是在开发机器上么？
在开发机器或者其他部署时，使用最新的JDK。
JDK设置参考：https://github.com/chatopera/chatopera-sample-java/issues/1

**Comment by hj123hj** [comment]
我是在开发 工具上跑起来的，jdk是最新的，我只运行了contact-center。需要依赖其他模块么？

**Comment by Samurais** [comment]
是java读取SSL的文件出错，从浏览器打开
```
https://nexus.chatopera.com/
```
信任一下该网址。

**Comment by hj123hj** [comment]
![image](https://user-images.githubusercontent.com/28702031/56583734-d6bf1b00-660c-11e9-8eaf-96ef3f814649.png)
![image](https://user-images.githubusercontent.com/28702031/56584192-d8d5a980-660d-11e9-85c6-1c89ca2f84f7.png)
全加了 还是不行

**Comment by Samurais** [comment]
感谢反馈，之前有用户用到过，后来他解决了，我忘记方案了。将来解决我再补充到这里。我现在没有复现，测试不了。

**Comment by Samurais** [comment]
应该是你的java环境读取ssl证书的地址和系统中存储ssl证书的地址不一致或没有权限。

**Comment by Samurais** [comment]
最合理的方式应该是用Java官方的SDK Installer安装JDK。
注意，是JDK，不是JRE。

**Comment by hj123hj** [comment]
我本地没有配置https，没有证书，全都是源代码拉下来默认的设置，集成机器人需要配置https吗？

**Comment by hj123hj** [comment]
果然是jdk的原因，重新官网下载安装就好，多谢。

**Comment by GangTimes** [comment]
我也遇到这个情况，更新了也解决不了

**Comment by Samurais** [comment]
> 我也遇到这个情况，更新了也解决不了

安装如下JDK，如果报错，发一下报错信息。
https://aws.amazon.com/cn/corretto/
