### ISSUE TITLE
客服机器人链接报java空指针

### ISSUE THREAD

**Issue by jydatatop** [chatopera/cosin#215]
客服后台报异常：
java.lang.NullPointerException
	at com.chatopera.cc.app.im.handler.ChatbotEventHandler.onConnect(ChatbotEventHandler.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
前提是：
1.在Chatopera 云服务平台已经定义了机器人。
2.在客服平台已经设置了对应的机器人。

**Comment by Samurais** [comment]
使用最新代码解决上述问题。
