### ISSUE TITLE
语音渠道对接freesitch外呼计划执行报错

### ISSUE THREAD

**Issue by 908305918** [chatopera/cosin#217]
# 描述
执行外呼计划，freeswitch报错
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at module.exports.conn.on (/home/cc-switch/app/fs.js:227:45)
    at module.exports.EventEmitter.emit (/home/cc-switch/app/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
    at module.exports.Connection._onEvent (/home/cc-switch/app/node_modules/modesl/lib/esl/Connection.js:795:10)
    at module.exports.EventEmitter.emit (/home/cc-switch/app/node_modules/eventemitter2/lib/eventemitter2.js:388:22)
    at module.exports.Parser._parseEvent (/home/cc-switch/app/node_modules/modesl/lib/esl/Parser.js:208:10)
    at module.exports.Parser._parseBody (/home/cc-switch/app/node_modules/modesl/lib/esl/Parser.js:100:10)
    at module.exports.Parser._parseHeaders (/home/cc-switch/app/node_modules/modesl/lib/esl/Parser.js:76:37)
    at module.exports.Parser._onData (/home/cc-switch/app/node_modules/modesl/lib/esl/Parser.js:36:21)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
![image](https://user-images.githubusercontent.com/5567858/66984404-38a89b00-f0ed-11e9-96e0-cb3b2977e96c.png)
请问这个variable_bridge_channel变量怎么设置
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
外呼问题在新版本中作为付费模块支持，在开源版本中不解决这类问题。
