### ISSUE TITLE
开发版本启动定时器一直执行一个拼接错误的sql

### ISSUE THREAD

**Issue by sheihaibushixiaogongzhu** [chatopera/cosin#298]
# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by sheihaibushixiaogongzhu** [comment]
2020-02-24 11:26:56.510 ERROR druid.sql.Statement - {conn-10005, pstmt-20525} execute error. select sessioncon0_.id as id1_92_, sessioncon0_.agentautoleave as agentaut2_92_, sessioncon0_.agentbusymsg as agentbus3_92_, sessioncon0_.agentctrlenter as agentctr4_92_, sessioncon0_.agentreplaytimeout as agentrep5_92_, sessioncon0_.agenttimeout as agenttim6_92_, sessioncon0_.agenttimeoutmsg as agenttim7_92_, sessioncon0_.creater as creater8_92_, sessioncon0_.createtime as createti9_92_, sessioncon0_.ctrlenter as ctrlent10_92_, sessioncon0_.distribution as distrib11_92_, sessioncon0_.enablequick as enableq12_92_, sessioncon0_.finessmsg as finessm13_92_, sessioncon0_.hourcheck as hourche14_92_, sessioncon0_.initmaxuser as initmax15_92_, sessioncon0_.lastagent as lastage16_92_, sessioncon0_.maxuser as maxuser17_92_, sessioncon0_.name as name18_92_, sessioncon0_.noagentmsg as noagent19_92_, sessioncon0_.notinwhmsg as notinwh20_92_, sessioncon0_.oqrdetailinput as oqrdeta21_92_, sessioncon0_.oqrdetailoutput as oqrdeta22_92_, sessioncon0_.oqrdetailurl as oqrdeta23_92_, sessioncon0_.oqrsearchinput as oqrsear24_92_, sessioncon0_.oqrsearchoutput as oqrsear25_92_, sessioncon0_.oqrsearchurl as oqrsear26_92_, sessioncon0_.orgi as orgi27_92_, sessioncon0_.otherquickplay as otherqu28_92_, sessioncon0_.otherssl as otherss29_92_, sessioncon0_.quality as quality30_92_, sessioncon0_.qualityscore as quality31_92_, sessioncon0_.quene as quene32_92_, sessioncon0_.quenetimeout as queneti33_92_, sessioncon0_.quenetimeoutmsg as queneti34_92_, sessioncon0_.resessiontimeout as resessi35_92_, sessioncon0_.retimeout as retimeo36_92_, sessioncon0_.retimeoutmsg as retimeo37_92_, sessioncon0_.satisfaction as satisfa38_92_, sessioncon0_.servicename as service39_92_, sessioncon0_.servicetimeout as service40_92_, sessioncon0_.servicetimeoutlimit as service41_92_, sessioncon0_.sessionmsg as session42_92_, sessioncon0_.sessiontimeout as session43_92_, sessioncon0_.successmsg as success44_92_, sessioncon0_.timeout as timeout45_92_, sessioncon0_.timeoutmsg as timeout46_92_, sessioncon0_.username as usernam47_92_, sessioncon0_.workinghours as working48_92_ from uk_sessionconfig sessioncon0_ [cs-schedule-6] 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'sessioncon0_.retimeoutmsg' in 'field list'
	at sun.reflect.GeneratedConstructorAccessor107.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by mukaiu** [comment]
数据库需要升级
