### ISSUE TITLE
tomcat启动后出现空指针异常，加载不了登陆页面

### ISSUE THREAD

**Issue by luqaing198855** [chatopera/cosin#353]
2020-08-14 23:42:36.492 ERROR o.s.b.w.s.ErrorPageFilter - Forwarding to error page from request [/login.html] due to exception [null] [http-nio-8035-exec-3] 
java.lang.NullPointerException: null
	at com.chatopera.cc.basic.MainContext.getCache(MainContext.java:1051)
	at com.chatopera.cc.basic.MainUtils.getSystemConfig(MainUtils.java:841)
	at com.chatopera.cc.controller.LoginController.login(LoginController.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

![01](https://user-images.githubusercontent.com/66345535/90267809-a433d400-de88-11ea-900c-95aa9f32e3ea.jpg)
![02](https://user-images.githubusercontent.com/66345535/90267617-66cf4680-de88-11ea-8b5b-3aa1bc8315f0.jpg)
![03](https://user-images.githubusercontent.com/66345535/90267624-6931a080-de88-11ea-8eed-d89127bac938.jpg)
![04](https://user-images.githubusercontent.com/66345535/90267626-69ca3700-de88-11ea-9bc7-8c772b745906.jpg)
![05](https://user-images.githubusercontent.com/66345535/90267632-6c2c9100-de88-11ea-8083-6ddca2b2c640.jpg)

)

**Comment by Samurais** [comment]
配置 Redis 服务了吗？
Redis服务正常吗？

**Comment by luqaing198855** [comment]
都配置redis的了 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai&amp;nbsp;Liang&amp;nbsp;Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月21日(星期五) 中午11:45
收件人: "chatopera/cosin";
抄送: "Author";
主题: Re: [chatopera/cosin] tomcat启动后出现空指针异常，加载不了登陆页面 (#353)





 
配置 Redis 服务了吗？
 Redis服务正常吗？
 
&mdash;

**Comment by Samurais** [comment]
抱歉，还是没看懂，参考购买春松客服大讲堂，里面有详细解释。

https://docs.chatopera.com/products/cskefu/training.html

关于开发环境，建议参考我们的文档：
https://docs.chatopera.com/products/cskefu/engineering.html

部署文档：
https://docs.chatopera.com/products/cskefu/deploy.html

如果还遇到问题，购买春松大讲堂可系统掌握二次开发技能。
